### ISSUE TITLE
` poetry run seagoat "definition" .` leads to error

### ISSUE THREAD

**Issue by kantord** [kantord/SeaGOAT#125]
Seems like paths are not normalized properly, as running the command above leads to an error when running it with the full path or even ~/repos/SeaGOAT worked on my computer.

The error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kantord/repos/SeaGOAT/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/seagoat/cli.py", line 169, in seagoat
    _, __, ___, server_address = load_server_info(server_info_file)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/seagoat/server.py", line 112, in load_server_info
    with open(server_info_file, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kantord/.cache/seagoat-servers/..json'
```

**Comment by kantord** [comment]
looks like this has fixed itself in the meantime, in any case I added a test for in https://github.com/kantord/SeaGOAT/pull/267
