### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kantord** [kantord/SeaGOAT#159]
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kantord/repos/SeaGOAT/seagoat/queue/base_queue.py", line 77, in _worker_function
    self._handle_task(context, task)
  File "/home/kantord/repos/SeaGOAT/seagoat/queue/base_queue.py", line 58, in _handle_task
    result = handler(context, *task.args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/seagoat/queue/task_queue.py", line 80, in handle_query
    context["seagoat_engine"].fetch_sync(
  File "/home/kantord/repos/SeaGOAT/seagoat/engine.py", line 156, in fetch_sync
    loop.run_until_complete(self.fetch(*args, **kwargs))
  File "/home/kantord/repos/SeaGOAT/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/seagoat/engine.py", line 140, in fetch
    self._results.extend(source["fetch"](self.query_string, limit_clue))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kantord/repos/SeaGOAT/seagoat/sources/chroma.py", line 50, in fetch
    files[path].add_line(line, distance)
  File "/home/kantord/repos/SeaGOAT/seagoat/result.py", line 99, in add_line
    self.line_texts[line - 1],
    ~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range

**Looks like this could be due to outdated data being in the database**

**Comment by kantord** [comment]
duplicate of https://github.com/kantord/SeaGOAT/issues/226
