### ISSUE TITLE
Support encodings other than utf-8

### ISSUE THREAD

**Issue by fedeb95** [kantord/SeaGOAT#227]
Hi, running seagoat-server start with a repository known to include strange characters (I don't know which, but it shouldn't be relevant; I've had similar errors by running OpenAI code embedding notebook) I get the following:

2023-09-20 16:14:22,735 Creating server...
2023-09-20 16:14:22,737 Starting worker thread...
2023-09-20 16:14:22,746 Serving on http://0.0.0.0:49999
2023-09-20 16:14:24,363 Checking repository for new changes
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\seagoat\lib\site-packages\seagoat\queue\base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner 
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\.local\pipx\venvs\seagoat\lib\site-packages\seagoat\queue\base_queue.py", line 81, in _worker_function
    self.handle_maintenance(context)
  File "C:\Users\user\.local\pipx\venvs\seagoat\lib\site-packages\seagoat\queue\task_queue.py", line 50, in handle_maintenance
    remaining_chunks_to_analyze = context["seagoat_engine"].analyze_codebase(
  File "C:\Users\user\.local\pipx\venvs\seagoat\lib\site-packages\seagoat\engine.py", line 82, in analyze_codebase
    self.repository.analyze_files()
  File "C:\Users\user\.local\pipx\venvs\seagoat\lib\site-packages\seagoat\repository.py", line 43, in analyze_files
    for line in iter(proc.stdout.readline, ""):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode      
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3682: character maps to <undefined>

I think seagoat should report the error, discard such files form the search, and go on.

**Comment by kantord** [comment]
that is interesting, could this be a windows specific issue? I don't know that much about Windows development but it seems like this could be due to files being encoded in a different way on Windows?

**Comment by fedeb95** [comment]
Could be. The files are probably not unicode, I would need more time to understand excatly what is the problem with them. Meanwhile, whichever the error, I don't think the server should stop, but exclude those file and go on processing the others.

**Comment by RicoElectrico** [comment]
Happens on WSL2 ubuntu as well (trying to index organicmaps/organicmaps)

**Comment by kantord** [comment]
ok, indeed it's being assumed that the files are utf8, and for anything that is not compatible with that it will fail. I am not sure what would be the best design to deal with this as it seems like it's not trivial to know what the encoding of a file is :thinking: at least so far the best cross platform approaches that I could find were using some heuristics

**Comment by HWoidt** [comment]
What about this library: https://pypi.org/project/chardet/
In case utf8 fails, we could fall back to using chardet for heuristically finding an alternative encoding.

**Comment by kantord** [comment]
fixed after merging https://github.com/kantord/SeaGOAT/pull/240 feel free to reopen if the problem persists
