### ISSUE TITLE
Exception "raise Empty” starting server for new repo

### ISSUE THREAD

**Issue by snej** [kantord/SeaGOAT#251]
I decided to try Seagoat on a different repo, a smaller one. (The other server process was not running anymore.) This time it failed immediately with two exceptions.

```
$  seagoat-server start ~/Projects/xxxxxx
2023-09-24 11:12:56,738 Creating server...
2023-09-24 11:12:56,739 Starting worker thread...
2023-09-24 11:12:56,741 Serving on http://0.0.0.0:61607
2023-09-24 11:12:57,971 Checking repository for new changes
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 81, in _worker_function
    self.handle_maintenance(context)
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 50, in handle_maintenance
    remaining_chunks_to_analyze = context["seagoat_engine"].analyze_codebase(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 84, in analyze_codebase
    return self._create_vector_embeddings(minimum_chunks_to_analyze)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 106, in _create_vector_embeddings
    for chunk in file.get_chunks():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/file.py", line 81, in get_chunks
    lines = self._get_file_lines()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/file.py", line 36, in _get_file_lines
    for i, line in enumerate(source_code_file.read().splitlines())
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 510: character maps to <undefined>
```

**Comment by kantord** [comment]
What kind of operating system are you using, and what kind of character encodings are used for the files?

This could be either a new bug that comes from fixing a previous bug, or some unexpected scenario that we have not seen yet

**Comment by kantord** [comment]
oh, and by the way, does this happen in all repos, or just one specific one?

**Comment by kantord** [comment]
looking at this issue: https://github.com/kantord/SeaGOAT/issues/250 maybe you copied the same error message twice?

**Comment by snej** [comment]
Nope, it logged both exceptions at the same time.

**Comment by kantord** [comment]
even in that case, in theory most encodings that are going to show up in any code repo should be supported :thinking:  so it might be that SeaGOAT is trying to read a file with the wrong encoding, even though the correct encoding should be supported

**Comment by kantord** [comment]
> Nope, it logged both exceptions at the same time.

I'm not 200.00% sure but I think that the first part: 

```
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/Users/snej/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty
```

should just be because it was the last thing in the queue :thinking:  or in any case, I am not sure that there is anything wrong wit the queue itself, as it seems like the error is really because of the encoding. feel free to reopen if the same error happens also without the encoding error being present
